version: 2

sources:
    - name: jaffle_shop
      database: analytics
      schema: dbt_mpassini_project
      tables: 
        - name: customers
          tests:
            - unique
            - not_null
        - name: orders
          tests:
            - unique
            - not_null